version: "3"

services:
  app:
    build: ./app
    command: gunicorn dcnet.wsgi:application --bind 0.0.0.0:8000
    volumes:
      -  static_files:/home/app/web/staticfiles
    expose:
      -  8080
    env_file:
      -  ./.env.app
    depends_on:
      -  db
 
  nginx:
    build: ./web
    volumes:
      -  static_files:/home/static
    ports:
      -  80:80
    depends_on:
      -  app

  db:
     image: postgres:13-alpine
     volumes:
      -  postgres_data:/var/lib/postgresql/data/
     env_file:
      -  ./.env.db

volumes:
  static_files:
  postgres_data:
